services:
  - type: web
    name: vul-detector-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: REACT_APP_API_URL
        value: https://vul-detector-backend.onrender.com
    healthCheckPath: /health
    autoDeploy: true
    region: oregon

  - type: web
    name: vul-detector-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://vul-detector-backend.onrender.com
    autoDeploy: true
    region: oregon 